Culture mapping rework
ParadoxGameConverters/EU4toVic3 pull request #181
Opened 2022-11-15 02:00 UTC by Elfangor567

- Updated Culture Mapping
- Now uses eu4group
- Now uses religion_group
- Now uses vic3 regions/states instead of eu4
- Now uses macros

2022-11-15 02:35 UTC, CarbonY26 commented
You're missing the `graphics = (insert architecture type here)` for every culture

2022-11-15 08:22 UTC, Zemurin requested changes

2022-11-15 08:22 UTC, Zemurin commented on EU4toV3/Data_Files/configurables/culture_map.txt
> +link = { vic3 = macedonian eu4 = bulgarian eu4 = serbian eu4 = montenegrin region = serbia_area region = rascia_area region = macedonia_area region = northern_greece_area region = albania_area }
Missed a bit here - old eu4 areas. Also, serbia_area would make all serbians in there macedonians, not good.

2022-11-15 08:22 UTC, Zemurin commented on EU4toV3/Data_Files/configurables/culture_map.txt
> +# Note: regions can be anything that makes sense, ie. region_north_germany, STATE_TUVA
please add superregions as well (continents): african_strategic_regions, east_asia_strategic_regions, etc.
We might as well use them for global stuff, if needed.

2022-11-19 08:39 UTC, Zemurin approved these changes

2022-11-19 08:39 UTC, merged