landshare prospective design
ParadoxGameConverters/EU4toVic3 pull request #201
Opened 2022-11-22 15:01 UTC by gawquon

Preparatory work for buildings module. Codify landshare formula for use in RGO cap calculations as described in #194.

2022-11-22 15:12 UTC, gawquon commented on EU4toV3/Source/V3World/ClayManager/ProvinceCount.h
> +{
Should I make a .cpp file just for this constructor?

2022-11-22 16:19 UTC, Zemurin requested changes

2022-11-22 16:19 UTC, Zemurin commented on EU4toV3/EU4toV3.vcxproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
This file shouldn't exist. It's a copy of something else, elsewhere. Please delete it.

2022-11-22 16:19 UTC, Zemurin commented on EU4toV3/EU4toV3.vcxproj.filters
> +﻿<?xml version="1.0" encoding="utf-8"?>
ditto.

2022-11-22 16:19 UTC, Zemurin commented on EU4toV3/Source/V3World/ClayManager/ProvinceCount.h
> +{
Yes, because it's a nontrivial constructor, or just move it into a State method.

2022-11-22 16:19 UTC, Zemurin commented on EU4toV3/Source/V3World/ClayManager/ProvinceCount.h
> +struct ProvinceCount
Rename to something semantic, PrimeLandCalculator. It doesn't just count provinces.
Alternatively, and more elegantly, just move that function to the State itself.

2022-11-22 16:19 UTC, Zemurin commented on EU4toV3/Source/V3World/ClayManager/StateLoader/Province.h
> +	void setPrime() { impassable = true; }
prime = true, yes?

2022-11-22 16:19 UTC, Zemurin commented on EU4toV3/Source/V3World/ClayManager/StateLoader/State.cpp
> +static int calculateProvincePower(const V3::ProvinceCount& theCount)
It's SubstatePrimeLandshare, not province power.

2022-11-23 07:10 UTC, gawquon commented on EU4toV3/Source/V3World/ClayManager/ProvinceTypeCounter.h
> +#include <ranges>
Remove these unnecessary includes

2022-11-23 08:42 UTC, Zemurin commented on EU4toV3/Source/V3World/ClayManager/StateLoader/State.cpp
> +	return theCount.every + (5 - 1) * theCount.prime - theCount.impassable;
What's the deal with (5 - 1)?

2022-11-23 08:54 UTC, gawquon commented on EU4toV3/Source/V3World/ClayManager/StateLoader/State.cpp
> +	return theCount.every + (5 - 1) * theCount.prime - theCount.impassable;
The coefficient is SPLIT_STATE_PRIME_LAND_WEIGHT - 1.  If the define ever changes from say 5 to 3 it's to make it easier to catch that the new coefficient is 2 and not mindlessly swap in 3. I guess I could have just left a comment to that effect, could also read in SPLIT_STATE_PRIME_LAND_WEIGHT from the defines but didn't seem worth it atm.

2022-11-23 08:56 UTC, gawquon commented on EU4toV3/Source/V3World/ClayManager/StateLoader/State.cpp
> +	return theCount.every + (5 - 1) * theCount.prime - theCount.impassable;
Also seeing now that my comment is incorrect

2022-11-24 08:39 UTC, Zemurin requested changes

2022-11-24 08:39 UTC, Zemurin commented on EU4toV3/Source/V3World/ClayManager/StateLoader/State.cpp
> +			auto theProvinceName = commonItems::remQuotes(provinceName);
we actually don't need remQuotes, they are stripped automatically. You can remove this here and above in upper lambdas.

2022-11-24 08:39 UTC, Zemurin commented on EU4toV3/Source/V3World/ClayManager/StateLoader/State.cpp
> +		std::transform(traits.begin(), traits.end(), traits.begin(), commonItems::remQuotes);
Yeah, drop this line, not needed. Also can drop related tests.

2022-11-24 08:39 UTC, Zemurin commented on EU4toV3/Source/V3World/ClayManager/StateLoader/State.cpp
> +		std::transform(arableResources.begin(), arableResources.end(), arableResources.begin(), commonItems::remQuotes);
ditto

2022-11-24 08:39 UTC, Zemurin commented on EU4toV3/Source/V3World/ClayManager/StateLoader/State.cpp
> +			cappedResources[resource] = std::stoi(amount);
Whenever using stoi, it's a good idea to wrap it in a try-catch block and catch the exception, if only so we can throw out a nice error when someone makes a typo inside. And move on instead of throwing an exception and dying.

2022-11-24 08:39 UTC, Zemurin commented on EU4toV3/Source/V3World/ClayManager/StateLoader/State.cpp
> +			substate->resources[resource] = substate->landshare * amount; // Intentionally truncated with an implicit int cast
Or, make it explicit using cast and round? So we can see it directly.

2022-11-24 08:39 UTC, Zemurin commented on EU4toV3/Source/V3World/ClayManager/SubState.h
> +	double landshare; // % of State's resources that are substate's
initialize primitives. 
double landshare=0;

2022-11-24 08:39 UTC, Zemurin commented on EU4toV3/Source/V3World/ClayManager/StateLoader/State.cpp
> +}
No, this is counterintuitive. Rather delete these testing functions as they don't do anything, and move the other two distribute* functions into public. You'll have to tell the state to actually distribute resources somehow anyway.

2022-11-24 11:43 UTC, Zemurin approved these changes

2022-11-24 11:45 UTC, merged