Estimate PM prevalences
ParadoxGameConverters/EU4ToVic3 pull request #572
Opened 2024-08-17 18:58 UTC by gawquon

- [ ] Add demand factor
- [ ] Rebalance weights
---
### Demand Building Component
- [x] ~~Load employment from PMs~~ (Already did, thanks past me.)
- [x] ~~Load input/output goods from PMs~~
- [x] Use average weight of PMs from EconManager config file. (Country by country basis)
- [ ] Predict ownership PMs based on country laws.
- [ ] Track available workers and Subsistence space.
- [ ] Track Jobs% and Culture% when building.
- [ ] Resolves a building's PMGroups to building's average net input/output/jobs.

### Balancing
- [ ] Have demand be primary factor, but allow the other weights to punch through at times.
- [ ] Add function to generate extra arable land for extra pop.
- [ ] Check additional bureaucracy cost incurred by nationalization, supplementary admin round if needed.

2024-10-23 21:04 UTC, Zemurin requested changes
Mostly semantics, looks very very good overall. I'm sure Idhrendur will find tons more though.

2024-10-24 21:39 UTC, gawquon commented on EU4ToVic3/Source/V3World/EconomyManager/Building/BuildingResources.cpp
> +			percent = p;
I grant that is the most literal definition. In my experience, (I don't know if it's just an American thing or Mathematician), the working definition of when we use fraction is to refer to x/y notation for rationals, and we use percent to refer to any decimal notation whether that's 0.70 or 70%.

Regardless, I'll switch it.

2024-10-24 21:55 UTC, gawquon commented on EU4ToVic3/Source/V3World/EconomyManager/Demand/MarketJobs.cpp
> +		unitEmployment[job] = amount / (popTypes.at(job).getDependentRatio().value_or(defaultRatio) + womenJobRate);
In order to /0, a mod would have to change the working_adult_ratio in a popType to 0; i.e. 100% dependents and 0% workers.

2024-10-24 22:57 UTC, gawquon commented on EU4ToVic3Tests/MapperTests/BuildingMapperTests/ProductionMethodMapperTests.cpp
> +	EXPECT_THAT(lawPMEstimates, testing::Contains(testing::Pair("pmg_ownership_capital_building_logging_camp", std::make_tuple(3, 1.0))));
4th pm, not 4th pmg. It's a map of what index to select in each pmg's pm vector.

```
pmg_ownership_capital_building_logging_camp = {
	production_methods = {
		pm_merchant_guilds_building_logging_camp
		pm_privately_owned_building_logging_camp
		pm_publicly_traded_building_logging_camp
		pm_government_run_building_logging_camp // this one
		pm_worker_cooperative_building_logging_camp
	}
}
```

2024-10-24 23:29 UTC, gawquon commented on EU4ToVic3/Source/V3World/EconomyManager/Demand/MarketJobs.cpp
> +	const double unitPop = std::accumulate(unitEmployment.begin(), unitEmployment.end(), 0.0, [](double sum, const auto& pair) {
unitPop is the maximum # of people who could be employed by 1 level of a building, accounting for the jobs created by ownership and urban centers, and all the dependents of those who work in the building.

The only way it could be 0 is if a building does not create any jobs. Which doesn't seem likely, but sure I guess PDX could do that one day, I'll add a check.

I've also renamed unitPop to unitEmploymentPop.

2024-10-24 23:40 UTC, gawquon commented on EU4ToVic3/Source/V3World/EconomyManager/EconomyManager.cpp
> +		investorWeights[type] /= totalWeight;
Those would be "national" or "local" investors. Also this function is turning the weights from configurbales/economy/ownership.txt into fractions on a country by country basis. I've refactored a couple things to hopefully paint a clearer picture there.

2024-10-25 02:56 UTC, Idhrendur reviewed
I'm about 29% through, will continue in the coming days. For the future, when you've got bits fairly stable, it doesn't hurt to spin them off into smaller PRs so we can review and approve faster.

2024-10-25 02:56 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/EconomyManager/Building/BuildingGroups.h
> +	[[nodiscard]] int getUrbanization(const std::optional<std::string>& theGroupName) const;
Building::GetBuildingGroup returns a string, so you could just take a string parameter instead of an optional<string> parameter.

2024-10-25 02:56 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/EconomyManager/Building/BuildingResources.h
As I usually ask, please add tests for this class.

2024-10-25 02:56 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/EconomyManager/Building/ProductionMethods/ProductionMethod.cpp
>  std::string V3::ProductionMethod::getType(const std::string& typeString)
Some tests for this function would clarify what it's doing.

2024-10-30 15:18 UTC, Idhrendur reviewed
86% reviewed

2024-11-10 07:23 UTC, Idhrendur reviewed
Sorry for the pause, 90% reviewed.

2024-11-10 07:23 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/EconomyManager/Demand/MarketJobs.cpp
> +		for (const auto& [job, amount]: ownershipEmployments.at(type)) // Account for the owner of the buildings.
Is it at all possible for ownershipEmployments to not have type? If it is possible, you should make sure to handle it in some way or another.

2024-11-10 07:23 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/EconomyManager/Demand/MarketJobs.cpp
> +		unitEmployment[job] = amount / (popTypes.at(job).getDependentRatio().value_or(defaultRatio) + womenJobRate);
You use `popTypes.at(job).getDependentRatio().value_or(defaultRatio) + womenJobRate` in at least a couple places. It'd be more clear if you shoved it into a well-named function in an anonymous namespace at the top of this file.

2024-11-10 07:23 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/EconomyManager/Demand/MarketJobs.cpp
> +	return amount;
```suggestion
       	subState->setJob("unemployed", 0);
	return amount - unemployed;
```

2024-11-10 07:23 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/EconomyManager/Demand/MarketJobs.cpp
> +		// Log(LogLevel::Warning) << "No subsistence workers available.";
If this is no longer needed, delete.

2024-11-10 07:23 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/EconomyManager/Demand/MarketJobs.cpp
> +	// }
If no longer needed, delete.

2024-11-10 07:23 UTC, Idhrendur commented on EU4ToVic3Tests/V3WorldTests/EconomyManagerTests/DemandTests/MarketJobsTests.cpp
> +TEST(V3World_MarketJobsTests, CreateSubsistenceNotEnoughLand)
Tests are more clear when named along the lines of FunctionExpectedResultWhenConditions. I'd guess this to be CreateSubsistenceLeavesUnemployedPopsWhenNotEnoughLand. Wordy, but quite clear. If possible rename this and other test names as appropriate.

2024-11-12 21:36 UTC, gawquon commented on EU4ToVic3/Source/V3World/EconomyManager/Building/BuildingResources.h
> +	void addJobs(const std::string& job, const double amount) { jobs[job] += amount; }
So, I discovered in my next PR that since we're hardcoding ports to Siberia and whatnot, there's going to be cases where we do have to build buildings when there isn't enough workforce. In that PR I abandon that absolute limits on building without workforce to allow for the hardcoded buildings, and allowing these estimates to go negative gives more accurate predictions. (It offsets the increase in expected workers elsewhere.)

Because the exact dependent to worker ratio is a little weird at game start, I don't see a benefit to exactly calculating what % a building is going to be filled when that estimate is likely to be off by about a similar amount. So I'd rather just let the negative jobs offset the extra positive ones until proven otherwise.

2024-11-12 22:09 UTC, gawquon commented on EU4ToVic3/Source/V3World/EconomyManager/Building/ProductionMethods/ProductionMethod.cpp
>  std::string V3::ProductionMethod::getType(const std::string& typeString)
added a comment and a separate test

2024-11-12 23:57 UTC, gawquon commented on EU4ToVic3/Source/V3World/EconomyManager/Demand/MarketJobs.cpp
> +		// Log(LogLevel::Warning) << "No subsistence workers available.";
At this point I was unsure whether or not it was going to be needed. That was determined in the next PR (don't need), and it is deleted there.

2024-11-12 23:57 UTC, gawquon commented on EU4ToVic3/Source/V3World/EconomyManager/Demand/MarketJobs.cpp
> +	// }
same as above

2024-11-13 00:00 UTC, gawquon commented on EU4ToVic3/Source/V3World/EconomyManager/Demand/MarketJobs.cpp
> +		unitEmployment[job] = amount / (popTypes.at(job).getDependentRatio().value_or(defaultRatio) + womenJobRate);
iirc Zem does private functions over anonymous namespaces

2024-11-13 00:44 UTC, gawquon commented on EU4ToVic3/Source/V3World/EconomyManager/Demand/MarketJobs.cpp
> +		for (const auto& [job, amount]: ownershipEmployments.at(type)) // Account for the owner of the buildings.
Not currently, but worth logging.

2024-11-17 21:38 UTC, Idhrendur approved these changes

2024-11-17 21:38 UTC, Idhrendur commented on EU4ToVic3Tests/V3WorldTests/PoliticalManagerTests/CountryTests/CountryTests.cpp
> +	V3::Pop pop0, pop1, pop2;
It would be more clear (and fewer lines) to use the constructor:
```suggestion
    V3:Pop pop0("english", "", "", 1000);
    V3:Pop pop1("german", "", "", 500);
    V3:Pop pop1("english", "", "", 500);
```

2024-11-17 21:38 UTC, Idhrendur commented on EU4ToVic3Tests/V3WorldTests/PoliticalManagerTests/CountryTests/CountryTests.cpp
> +TEST(V3World_CountryTests, HasAnyOfLawUnlockingPositiveCase)
```suggestion
TEST(V3World_CountryTests, HasAnyOfLawUnlockingIsTrueIfAnyOfLawsArePresent)
```

2024-11-17 21:38 UTC, Idhrendur commented on EU4ToVic3Tests/V3WorldTests/PoliticalManagerTests/CountryTests/CountryTests.cpp
> +TEST(V3World_CountryTests, HasAnyOfLawUnlockingNegativeCase)
```suggestion
TEST(V3World_CountryTests, HasAnyOfLawUnlockingFalseIfNoneOfLawsPresent)
```

2024-11-17 21:38 UTC, Idhrendur commented on EU4ToVic3Tests/V3WorldTests/PoliticalManagerTests/CountryTests/CountryTests.cpp
> +TEST(V3World_CountryTests, HasAnyOfLawBlockingPositiveCase)
```suggestion
TEST(V3World_CountryTests, HasAnyOfLawBlockingTrueIfAnyOfLawsArePresent)
```

2024-11-17 21:38 UTC, Idhrendur commented on EU4ToVic3Tests/V3WorldTests/PoliticalManagerTests/CountryTests/CountryTests.cpp
> +TEST(V3World_CountryTests, HasAnyOfLawBlockingNegativeCase)
```suggestion
TEST(V3World_CountryTests, HasAnyOfLawBlockingFalseIfNoneOfLawsPresent)
```

2024-11-17 21:38 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/PoliticalManager/Country/Country.cpp
> +	}
Add a test for the empty laws case, especially since that's the difference between this and hasAnyOfLawBlocking().

2024-11-17 21:38 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/PoliticalManager/Country/Country.cpp
> +	}
Ditto

2024-11-17 21:38 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/EconomyManager/Demand/MarketJobs.h
> +	// Returns the level of subsistence buildings downsized.
```suggestion
	// For a given popType, what % of that popType have jobs?
	static double calculateWorkerDependencyRatio(const PopType& popType, double defaultRatio, double womenJobRate);
	// How many people do x number of jobs support?
	static double getWorkersPlusDependents(double amountOfJobs, const PopType& popType, double defaultRatio, double womenJobRate);

	// Returns the amount of jobs with no unemployed available.
	static double hireFromUnemployed(double amount, const std::shared_ptr<SubState>& subState);
	// Returns the level of subsistence buildings downsized.
```

Since these aren't used outside the class, it would be better to put them in an anonymous namespace at the top of the .cpp file and not expose them in the interface.

2024-11-17 21:38 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/EconomyManager/Demand/MarketTracker.cpp
> +	out << std::setfill(' ');
FWIW, this becomes easier (and easier to read) by pulling in fmt::format (to be replaced by std::format when our runners can take it).

2024-11-17 21:38 UTC, Idhrendur commented on EU4ToVic3Tests/V3WorldTests/EconomyManagerTests/DemandTests/MarketTrackerTests.cpp
Remember to write tests here, as much as possible.

2024-11-17 21:38 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/EconomyManager/EconomyManager.h
> +	void establishBureaucracy(const std::shared_ptr<Country>& country, const std::map<std::string, Law>& lawsMap, const Vic3DefinesLoader& defines) const;
```suggestion
	void establishBureaucracy(const Country& country, const std::map<std::string, Law>& lawsMap, const Vic3DefinesLoader& defines) const;
```

You're not taking (shared) ownership of the country, so just take a reference to it.

2024-11-17 21:38 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/EconomyManager/EconomyManager.h
> +	void hardcodePorts(const std::shared_ptr<Country>& country) const;
```suggestion
	void hardcodePorts(const Country& country) const;
```

Ditto.

2024-11-17 21:38 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/EconomyManager/EconomyManager.cpp
> +		for (const auto& building: subState->getBuildings())
Are you getting a shared_ptr to a building? Maybe see if you can dereference it immediately in the loop construct.

2024-11-17 21:38 UTC, Idhrendur commented on EU4ToVic3/Source/V3World/EconomyManager/EconomyManager.h
> +	void integrateHardcodedBuildings(const std::shared_ptr<Country>& country,
```suggestion
	void integrateHardcodedBuildings(const Country& country,
```
Ditto

2025-02-06 05:58 UTC, gawquon commented on EU4ToVic3Tests/V3WorldTests/EconomyManagerTests/DemandTests/MarketTrackerTests.cpp
Addressed in next PR

2025-02-07 21:56 UTC, Zemurin approved these changes

2025-02-07 21:56 UTC, merged