Fronter config, mod loading, cleanup
ParadoxGameConverters/EU4toVic3 pull request #9
Opened 2021-05-24 11:54 UTC by Zemurin

2021-05-24 12:35 UTC, IhateTrains approved these changes

2021-05-24 12:35 UTC, IhateTrains commented on EU4toV3/Data_Files/fronter-configuration.txt
> +	searchPath = "Paradox Interactive\Victoria II\mod"
```suggestion
	searchPath = "Paradox Interactive\Victoria III\mod"
```

2021-05-24 12:35 UTC, IhateTrains commented on EU4toV3/Source/Configuration/Configuration.cpp
> +	if (!commonItems::DoesFileExist(Vic3Path + "/victoria2.exe") && !commonItems::DoesFileExist(Vic3Path + "/Vic3game") &&
Are you intentionally reverting this?

2021-05-24 12:38 UTC, Zemurin commented on EU4toV3/Source/Configuration/Configuration.cpp
> +	if (!commonItems::DoesFileExist(Vic3Path + "/victoria2.exe") && !commonItems::DoesFileExist(Vic3Path + "/Vic3game") &&
Yeah, I need the converter operational under faux paths, otherwise it won't work. I'll fix it properly once we have the path in place.

2021-05-24 12:42 UTC, Zemurin commented on EU4toV3/Data_Files/fronter-configuration.txt
> +	searchPath = "Paradox Interactive\Victoria II\mod"
same reason, I reverted to II because that's a folder that actually exists on my computer. I imagine vic3 will use "3" in directory name.

2021-05-25 03:18 UTC, Idhrendur requested changes

2021-05-25 03:18 UTC, Idhrendur commented on EU4toV3/Source/EU4World/Mods/Mods.cpp
> +void EU4::Mods::loadMods(Configuration& configuration)
It's best to avoid in/out parameters. Instead, return a reference to usableMods, and have the caller of loadMods() call setEU4Mods() with it.

2021-05-25 03:18 UTC, Idhrendur commented on EU4toV3/Source/EU4World/World.h
> +	std::shared_ptr<Configuration> configuration;
Similarly, consider if it's really necessary for EU4::World to co-own configuration. It looks like you're only saving a single parameter to registerKeys() at the costs of a more tightly coupled design, an additional dereference every time you want to use the configuration, and a more fragmented memory layout.

Yes, it's small consequences here, but it's also a matter of building a habit of being judicious with shared_ptr so you don't accidentally use it where it might have bigger consequences (as with Vic2 pops, where there's so many that little things up to big changes in runtime and memory use).

2021-05-25 03:18 UTC, Idhrendur commented on EU4toV3/Source/V3World/V3World.cpp
> +	std::ofstream output2("output/" + outputName + "/descriptor.mod");
You can reuse output with .open()

2021-05-25 03:18 UTC, Idhrendur commented on EU4toV3/Source/V3World/Output/outModFile.h
> +class ModFile
The class name should match the file name, else its confusing to readers.

2021-05-25 03:18 UTC, Idhrendur commented on EU4toV3/Source/V3World/Output/outModFile.h
> +class ModFile
Also, a class seems unnecessary here. Just have a freestanding function and pass it the name.

2021-05-25 08:35 UTC, Zemurin commented on EU4toV3/Source/EU4World/Mods/Mod.cpp
> +	registerRegex("path|archive", [this](const std::string& unused, std::istream& theStream) {
Yes.
Also, yes.

2021-05-25 08:37 UTC, Zemurin commented on EU4toV3/Source/EU4World/Mods/Mods.h
> +	std::map<std::string, std::string> possibleMods;			  // name, absolute path to mod directory
I don't see anything but clang's whitespace. when it sees comments on subsequent lines, it likes to order comments visually one beneath the other.

2021-05-25 08:42 UTC, Zemurin commented on EU4toV3/Source/EU4World/World.h
> +	std::shared_ptr<Configuration> configuration;
This is a special use case here where I'd go against your advice. Yes, World only writes to configuration once to set the mods, but it's used in virtually every function it calls - every mapper it invokes needs to have configuration passed to it so it can grab paths, mods and the rest, and nonmappers still need to check for config options sometimes. It's visually cleaner to do this with a local pointer to configuration, than to spam the functions with unnecessary arguments.

2021-05-25 08:59 UTC, Zemurin commented on EU4toV3/Source/EU4World/World.h
> +	std::shared_ptr<Configuration> configuration;
Actually, I know this is bad, but I did enjoy the freedom of calling upon instanced theConfiguration from wherever I needed, and there were tons of those calls. Most of them were in V2world though as that part most often needed to check against config options and vic2 paths, but mappers as well as every mapper needed multiple mathing solutions. I may yet change this in EU4World to store only the paths locally and leave config alone, and in V2world do a similar thing, extract what's commonly used and store that locally. But Configuration is a convenient container for exactly that purpose, and while it's often dereferenced, it's done only once per class, so in grand scheme it's not that expensive.

2021-05-25 10:50 UTC, Zemurin commented on EU4toV3/Source/EU4World/World.h
> +	std::shared_ptr<Configuration> configuration;
See, that's exactly what I pay you for. I've ended up drastically simplifying the whole organization. Configuration is now just an initializer/helper class used to kickstart the conversion. Everything else is now neat simple and clear.

2021-05-25 11:34 UTC, merged